# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(252, 152)
        self.lb_count = QtWidgets.QLabel(parent=Form)
        self.lb_count.setGeometry(QtCore.QRect(0, 0, 251, 151))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(20)
        self.lb_count.setFont(font)
        self.lb_count.setText("")
        self.lb_count.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_count.setObjectName("lb_count")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
